"""Generate a standalone `clizard_main.py` that wraps a repo's existing
main() with tclizard_main clizard interface, using .clizard for display settings.
"""
import inspect
from pathlib import Path

from .discover import find_main, settings_from_main
from .clizard_file import ensure_clizard_file
from .git_info import get_git_info

TEMPLATE = '''"""Auto-generated by clizard. Wraps {entry_module}.main() with the
clizard interactive interface. Re-run `clizard --scaffold` to regenerate.
"""
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent / "{entry_dir}"))

from {entry_module} import main as _original_main
# Prefer the local `clizard` package if present; fall back to `genericli` for
# standalone generated scripts that expect that external package.

from clizard import GenericCLI
from clizard.clizard_file import load_clizard_file

REPO_PATH = str(Path(__file__).parent.resolve())


def build_cli():
    clz = load_clizard_file(REPO_PATH)

    settings = {settings!r}

    cli = GenericCLI(
        app_name=clz.get("app_name") or {app_name!r},
        ascii_art=clz.get("ascii_art"),
        accent_color=clz.get("accent_color", "#d97757"),
        settings=settings,
        tips=clz.get("tips"),
        updates=clz.get("updates"),
    )
    cli.arg_meta = {arg_meta!r}

    @cli.command("/run", "Run {entry_module}.main() with current settings")
    def _cmd_run(prompt):
        cli.status("Running...")
{run_body}
        if result is not None:
            cli.assistant_message(str(result))

    return cli


def main():
    build_cli().run()


if __name__ == "__main__":
    main()
'''

# main() takes plain keyword arguments -> call it directly with them.
KWARGS_RUN_BODY = """        call_kwargs = {k: cli.config.get(k) for k in settings}
        result = _original_main(**call_kwargs)"""

# main() takes no arguments and builds its own argparse.ArgumentParser()
# internally, reading sys.argv -- so rebuild sys.argv from the settings
# (using each setting's recorded --flag) and call main() with no arguments.
ARGV_RUN_BODY = """        argv = [sys.argv[0]]
        for name, meta in cli.arg_meta.items():
            flag = meta.get("flag")
            if not flag:
                continue
            val = cli.config.get(name)
            if val is None:
                continue
            if meta.get("is_flag"):
                if val:
                    argv.append(flag)
            else:
                argv.extend([flag, str(val)])
        old_argv = sys.argv
        sys.argv = argv
        try:
            result = _original_main()
        finally:
            sys.argv = old_argv"""


def generate_clizard_main(repo_path=".", output_name="clizard_main.py"):
    """Write a clizard_main.py at the repo root. Returns the output Path,
    or raises RuntimeError if no main() could be found.

    The previous default filename `clizard.py` shadows the `clizard` package when
    executed from the repo root (Python will import the local `clizard.py` file as
    the `clizard` module, making `from clizard import ...` fail). Use
    `clizard_main.py` to avoid that naming collision.
    """
    repo_path = Path(repo_path).resolve()
    module, main_func, entry_file = find_main(str(repo_path))

    if main_func is None:
        raise RuntimeError(f"No main() found under {repo_path}; nothing to wrap.")

    settings, arg_meta, call_style = settings_from_main(main_func)
    safe_arg_meta = {
        name: {
            "choices": info["choices"],
            # Only a plain string type name (e.g. "int") is safe to embed
            # in the generated source; a real class's repr (e.g. "<class
            # 'int'>") is not valid Python syntax inside a dict literal.
            "type": info["type"] if isinstance(info.get("type"), str) else None,
            "help": info["help"],
            "flag": info.get("flag"),
            "is_flag": info.get("is_flag", False),
        }
        for name, info in arg_meta.items()
    }
    run_body = ARGV_RUN_BODY if call_style == "argv" else KWARGS_RUN_BODY
    clz = ensure_clizard_file(str(repo_path))

    entry_file = Path(entry_file)
    entry_module = entry_file.stem  # "__main__" or "main"
    entry_dir = entry_file.parent.relative_to(repo_path) if entry_file.parent != repo_path else "."

    # __main__.py can't be imported by stem name; use the package instead.
    if entry_module == "__main__":
        entry_module = entry_file.parent.name
        entry_dir = entry_file.parent.parent.relative_to(repo_path) if entry_file.parent.parent != repo_path else "."

    code = TEMPLATE.format(
        entry_module=entry_module,
        entry_dir=str(entry_dir),
        app_name=clz.get("app_name") or repo_path.name,
        settings=settings,
        arg_meta=safe_arg_meta,
        run_body=run_body,
    )

    # The sys.path insertion above is computed as Path(__file__).parent /
    # entry_dir, where entry_dir is relative to repo_path -- so the
    # generated file must actually live at repo_path for that math to
    # resolve. Writing it anywhere else (e.g. inside the package
    # containing main()) silently breaks the import.
    if entry_file.parent.exists():
        out_path = entry_file.parent / output_name
    else:
        out_path = repo_path / output_name

    # Write file
    out_path.write_text(code)
    return out_path


def clizardmake_cli(path=None):
    """Console entrypoint wrapper that uses the current working directory by default.

    This function is intended for the `clizardmake` console_scripts entry point so
    that running `clizardmake` will operate on the directory where it is executed.
    """
    import os
    import sys

    repo_path = Path(path or os.getcwd())

    try:
        out = generate_clizard_main(repo_path=str(repo_path))
        # Print the output path so the user sees where the file was written
        print(f'clizard main file written to: {out}')
    except RuntimeError as e:
        print(str(e), file=sys.stderr)
        sys.exit(1)
