"""Generate a standalone `clizard_main.py` that wraps a repo's existing
main() with tclizard_main clizard interface, using .clizard for display settings.
"""
import inspect
from pathlib import Path

from .discover import find_main, settings_from_main
from .clizard_file import ensure_clizard_file, save_clizard_file
from .git_info import get_git_info

TEMPLATE = '''"""Auto-generated by clizard. Wraps {entry_module}.main() with the
clizard interactive interface. Re-run `clizard --scaffold` to regenerate.
"""
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent / "{entry_dir}"))

from {entry_module} import main as _original_main
# Prefer the local `clizard` package if present; fall back to `genericli` for
# standalone generated scripts that expect that external package.

from clizard import GenericCLI
from clizard.clizard_file import load_clizard_file

REPO_PATH = str(Path(__file__).parent.resolve())

# Fallback values baked in at generation time, used only if .clizard is
# missing these keys (e.g. it predates this feature, or was hand-edited).
_DEFAULT_SETTINGS = {settings!r}
_DEFAULT_ARG_META = {arg_meta!r}
_DEFAULT_CALL_STYLE = {call_style!r}


def build_cli():
    clz = load_clizard_file(REPO_PATH)

    # Settings/arg_meta/call_style live in .clizard so that edits made via
    # `/settings` while running `clizard` interactively (or by hand-editing
    # .clizard) are picked up here too, without needing to re-scaffold.
    settings = clz.get("settings") or _DEFAULT_SETTINGS
    arg_meta = clz.get("arg_meta") or _DEFAULT_ARG_META
    call_style = clz.get("call_style") or _DEFAULT_CALL_STYLE

    cli = GenericCLI(
        app_name=clz.get("app_name") or {app_name!r},
        ascii_art=clz.get("ascii_art"),
        accent_color=clz.get("accent_color", "#d97757"),
        settings=settings,
        tips=clz.get("tips"),
        updates=clz.get("updates"),
    )
    cli.arg_meta = arg_meta

    @cli.command("/run", "Run {entry_module}.main() with current settings")
    def _cmd_run(prompt):
        cli.status("Running...")
        if call_style == "argv":
            # main() takes no arguments and parses its own argparse
            # parser internally -- rebuild sys.argv from settings instead.
            argv = [sys.argv[0]]
            for name, meta in cli.arg_meta.items():
                flag = meta.get("flag")
                if not flag:
                    continue
                val = cli.config.get(name)
                if val is None:
                    continue
                if meta.get("is_flag"):
                    if val:
                        argv.append(flag)
                else:
                    argv.extend([flag, str(val)])
            old_argv = sys.argv
            sys.argv = argv
            try:
                result = _original_main()
            finally:
                sys.argv = old_argv
        else:
            call_kwargs = {{k: cli.config.get(k) for k in settings}}
            result = _original_main(**call_kwargs)
        if result is not None:
            cli.assistant_message(str(result))

    return cli


def main():
    build_cli().run()


if __name__ == "__main__":
    main()
'''


def generate_clizard_main(repo_path=".", output_name="clizard_main.py"):
    """Write a clizard_main.py at the repo root. Returns the output Path,
    or raises RuntimeError if no main() could be found.

    The previous default filename `clizard.py` shadows the `clizard` package when
    executed from the repo root (Python will import the local `clizard.py` file as
    the `clizard` module, making `from clizard import ...` fail). Use
    `clizard_main.py` to avoid that naming collision.
    """
    repo_path = Path(repo_path).resolve()
    module, main_func, entry_file = find_main(str(repo_path))

    if main_func is None:
        raise RuntimeError(f"No main() found under {repo_path}; nothing to wrap.")

    settings, arg_meta, call_style = settings_from_main(main_func)
    safe_arg_meta = {
        name: {
            "choices": info["choices"],
            # Only a plain string type name (e.g. "int") is safe to embed
            # in the generated source; a real class's repr (e.g. "<class
            # 'int'>") is not valid Python syntax inside a dict literal.
            "type": info["type"] if isinstance(info.get("type"), str) else None,
            "help": info["help"],
            "flag": info.get("flag"),
            "is_flag": info.get("is_flag", False),
        }
        for name, info in arg_meta.items()
    }
    run_body_call_style = call_style

    entry_file = Path(entry_file)
    entry_module = entry_file.stem  # "__main__" or "main"
    entry_dir = entry_file.parent.relative_to(repo_path) if entry_file.parent != repo_path else "."

    # Both clizard_main.py and .clizard always live at repo_path (the repo
    # root), never inside the subdirectory/package containing main(). This
    # matches the sys.path math below (Path(__file__).parent / entry_dir,
    # with entry_dir relative to repo_path) and keeps a single, predictable
    # location -- the same one `clizard` itself uses for .clizard.
    out_path = repo_path / output_name

    # Persist the discovered settings/arg_meta/call_style into .clizard so
    # they're loaded at runtime by build_cli() above -- this also means
    # edits made via `/settings` (or by hand-editing .clizard) carry over
    # without needing to re-scaffold, and clizard_main.py can be regenerated
    # later without losing customizations made elsewhere in .clizard.
    clz = ensure_clizard_file(str(repo_path))
    clz["settings"] = settings
    clz["arg_meta"] = safe_arg_meta
    clz["call_style"] = call_style
    save_clizard_file(clz, str(repo_path))

    # __main__.py can't be imported by stem name; use the package instead.
    if entry_module == "__main__":
        entry_module = entry_file.parent.name
        entry_dir = entry_file.parent.parent.relative_to(repo_path) if entry_file.parent.parent != repo_path else "."

    code = TEMPLATE.format(
        entry_module=entry_module,
        entry_dir=str(entry_dir),
        app_name=clz.get("app_name") or repo_path.name,
        settings=settings,
        arg_meta=safe_arg_meta,
        call_style=run_body_call_style,
    )

    # Write file
    out_path.write_text(code)
    return out_path


def clizardmake_cli(path=None):
    """Console entrypoint wrapper that uses the current working directory by default.

    This function is intended for the `clizardmake` console_scripts entry point so
    that running `clizardmake` will operate on the directory where it is executed.
    """
    import os
    import sys

    repo_path = Path(path or os.getcwd())

    try:
        out = generate_clizard_main(repo_path=str(repo_path))
        # Print the output path so the user sees where the file was written
        print(f'clizard main file written to: {out}')
    except RuntimeError as e:
        print(str(e), file=sys.stderr)
        sys.exit(1)
